# Adoptium API
adoptium.api.url=https://api.adoptium.net
adoptium.api.path.available_releases=/v3/info/available_releases
adoptium.api.path.version=/v3/version/
adoptium.api.path.assets.version=/v3/assets/version/%s?architecture=%s&heap_size=normal&image_type=jdk&os=%s&page=0&page_size=1&project=jdk&sort_method=DEFAULT&sort_order=DESC&vendor=eclipse
adoptium.api.path.assets.feature_releases=/v3/assets/feature_releases/%s/ga?architecture=%s&heap_size=normal&image_type=jdk&os=%s&page=0&page_size=1&sort_method=DEFAULT&sort_order=DESC&vendor=eclipse
adoptium.api.path.info.release_version=/v3/info/release_versions?page=0&page_size=1&project=jdk&release_type=ga&semver=false&sort_method=DEFAULT&sort_order=DESC&vendor=eclipse&version=%%5B%d%%2C%d%%5D

# Warp Packer Hashs
warp.linux.x64=1ee2dfb576ef8b06ef31d86d6d376f447ea02829e3474948b9ee07ec4c9a829c
warp.linux.aarch64=6540f103452b19e818999198eb96763e0a30de2c78d61019ba442396e9a36c3d
warp.macos.x64=785af8bc23ffa6259b599c95dcbfe0a9104d54f3d06ded4b723b4ed71929584c
warp.macos.aarch64=9c36ee68d0d6e694d2cacf97c658553e85d1edcb759019772ab26216c8955b2f
warp.windows.x64=866ba929c79a5406dc5d52acac6b6fa0d9c41c81d07aecef61d4dcde0bab881f
warp.windows.aarch64=3a834b702f00818b89cf0b08debda2b718f634fbf913c04d3613da94025d520c

# Warp-Packer URLs
warp.github.base.url=https://github.com/kirbylink/warp/releases/latest/download
warp.linux.x64.url=${warp.github.base.url}/linux-x64.warp-packer
warp.macos.x64.url=${warp.github.base.url}/macos-x64.warp-packer
warp.windows.x64.url=${warp.github.base.url}/windows-x64.warp-packer.exe
warp.linux.aarch64.url=${warp.github.base.url}/linux-aarch64.warp-packer
warp.macos.aarch64.url=${warp.github.base.url}/macos-aarch64.warp-packer
warp.windows.aarch64.url=${warp.github.base.url}/windows-aarch64.warp-packer.exe