# Adoptium API
adoptium.api.url=https://api.adoptium.net
adoptium.api.path.available_releases=/v3/info/available_releases
adoptium.api.path.version=/v3/version/
adoptium.api.path.assets.version=/v3/assets/version/%s?architecture=%s&heap_size=normal&image_type=jdk&os=%s&page=0&page_size=1&project=jdk&sort_method=DEFAULT&sort_order=DESC&vendor=eclipse
adoptium.api.path.assets.feature_releases=/v3/assets/feature_releases/%s/ga?architecture=%s&heap_size=normal&image_type=jdk&os=%s&page=0&page_size=1&sort_method=DEFAULT&sort_order=DESC&vendor=eclipse
adoptium.api.path.info.release_version=/v3/info/release_versions?page=0&page_size=1&project=jdk&release_type=ga&semver=false&sort_method=DEFAULT&sort_order=DESC&vendor=eclipse&version=%%5B%d%%2C%d%%5D

# Warp Packer Hashs
warp.linux.x64=add6f937db8b9207d1bb81a900ef609f41875f07c6c8b2d596bfc134c8f285ff
warp.linux.aarch64=872c0fefd4fc3988a3ac47a96bcc161c7a464a0c92234b4836186152c41818e7
warp.macos.x64=311bd238d087ea92f486d3d754a0f11826d9bd49d6f8ae849e5d6f6089a2e9c9
warp.macos.aarch64=ee123e3af8bbf7ab6abb8c9cb451ef5c3c8c654b0a01d3f81e84dab498b649ae
warp.windows.x64=483726e0eb10a43167c03c8e4f27a2901741affd245e5ec8ed45509f9dcd7a8a
warp.windows.aarch64=ed0bb8de43eee3f8867e4e8bdac5e3bbbf447239285c59abcfcd1610e76b0b21

# Warp-Packer URLs
warp.github.base.url=https://github.com/kirbylink/warp/releases/latest/download
warp.linux.x64.url=${warp.github.base.url}/linux-x64.warp-packer
warp.macos.x64.url=${warp.github.base.url}/macos-x64.warp-packer
warp.windows.x64.url=${warp.github.base.url}/windows-x64.warp-packer.exe
warp.linux.aarch64.url=${warp.github.base.url}/linux-aarch64.warp-packer
warp.macos.aarch64.url=${warp.github.base.url}/macos-aarch64.warp-packer
warp.windows.aarch64.url=${warp.github.base.url}/windows-aarch64.warp-packer.exe